### PR TITLE
Fixed null parameter not handled in MySQL prepared statement

### PR DESCRIPTION
**Pull request by matcracker**

### CODE REVIEW

**Comment by SOF3** [comment]
Why is it `s` to be specific?

**Comment by matcracker** [comment]
it shouldn't make any difference because mysql will automatically handle behind the scenes.

**Comment by SOF3** [comment]
I'm thinking if it's better to add a `?` modifier to the PSF syntax so that null is not allowed normally.

speaking of that... I thought I already added that? or did I misremember?

**Comment by matcracker** [comment]
oh wait, I didn't rightly specify in the PR description. This bug is only generated when using `raw` functions. The null value is already handled in the PSF (like `?string`)

**Comment by SOF3** [comment]
What is passed from the normal execute functions if it is nullable?

**Comment by matcracker** [comment]
It is passed as ["NULL" ](https://github.com/poggit/libasynql/blob/master/libasynql/src/poggit/libasynql/generic/MysqlStatementImpl.php#). I tried to do the same but it always considers it as string.

**Comment by SOF3** [comment]
But why is this different from the usual one? That sounds fishy.

**Pull request closed without merging**
