### PR TITLE
Improved exception error when .sql files are not preset in "resources" folder.

### PR DESCRIPTION
**Pull request by matcracker**

### CODE REVIEW

**Review by SOF3 — CHANGES_REQUESTED** [review]
This will open an unclosed stream and result in a resource leak.
Consider performing this change in the loadQueryFile implementation.

**Comment by matcracker** [comment]
How can it open a null resource stream? The getResource() already checks the file, if it exists will open the stream else not.

**Comment by matcracker** [comment]
I can move the condition inside the function, but in any case it can't generate a resource leak

**Comment by SOF3** [comment]
getResource opens a new stream if possible. If it is non null, you are ignoring the stream.

**Comment by SOF3** [comment]
Also please rebase on latest master. See the merge conflicts.

**Comment by SOF3** [comment]
Please *rebase* from poggit:master, not to cherry-pick all your local changes to the old upstream.
image

**Comment by matcracker** [comment]
Done?

**Pull request closed without merging**
